version: "3.9"

services:

  postgres:
    image: postgres:11
    ports:
        - "5432:5432"
    environment:
        POSTGRES_DB: "commit-notifier"
        POSTGRES_USER: "commit-notifier"
        POSTGRES_PASSWORD: "commit-notifier"
